{
  "name": "corazon-huasteco-vite",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "test": "testcafe chrome tests/*.test.js",
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint src --ext js,jsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@fontsource/roboto": "^5.0.3",
    "@mui/icons-material": "^5.11.16",
    "@mui/lab": "^5.0.0-alpha.134",
    "@mui/material": "^5.13.5",
    "@mui/x-date-pickers": "^6.8.0",
    "aos": "^2.3.4",
    "axios": "^1.4.0",
    "chart.js": "^4.3.0",
    "date-fns": "^2.30.0",
    "dayjs": "^1.11.8",
    "firebase": "^9.22.2",
    "firebase-tools": "^12.4.0",
    "formik": "^2.4.2",
    "https-browserify": "^1.0.0",
    "moment": "^2.29.4",
    "react": "^18.2.0",
    "react-chartjs-2": "^5.2.0",
    "react-dom": "^18.2.0",
    "react-leaflet": "^4.2.1",
    "react-router-dom": "^6.13.0",
    "react-useanimations": "^2.10.0",
    "semantic-ui-react": "^2.1.4",
    "stream-http": "^3.2.0",
    "yup": "^1.2.0",
    "spiral/roadrunner": "^2.4"
  },
  "devDependencies": {
    "@types/react": "^18.0.37",
    "@types/react-dom": "^18.0.11",
    "@vitejs/plugin-react": "^4.0.0",
    "eslint": "^8.38.0",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.3.4",
    "vite": "^4.3.9"
  }
}
