name: TestCafe Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install TestCafe
      run: npm install -g testcafe

    - name: Install project dependencies
      run: npm install

    - name: Run TestCafe tests Access
      run: testcafe chromium:headless ./tests/access.js

    - name: Run TestCafe tests Enlaces
      run: npm test ./tests/test_renderizado_sobre_nosotros.js
      
    - name: Run TestCafe tests Renderizado sobre Nosotros
      run: npm test ./tests/test_renderizado_sobre_nosotros.js
      
    - name: Run TestCafe tests Register
      run: testcafe chromium:headless ./tests/register.js



